### ISSUE TITLE
Change the system UI top bar

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#1]
Change it to look like this
![image](https://user-images.githubusercontent.com/89146189/195904928-a2677cd5-788f-4fa8-8998-cc979434a3af.png)

**Comment by S-Parker7000** [comment]
Assign me this issue

**Comment by ashiskumarnaik** [comment]
@adityabisht02 I would look to work on this issue. Assign me.

**Comment by adityabisht02** [comment]
Sure !
