### ISSUE TITLE
Want to add Contributing Guidelines... 

### ISSUE THREAD

**Issue by MohammadKaif1** [adityabisht02/BetterPoll-Android#12]

**Comment by adityabisht02** [comment]
Sure go ahead

**Comment by adityabisht02** [comment]
You can add a contributing.md

**Comment by MohammadKaif1** [comment]
@adityabisht02  can you please attach a tag of hacktoberfest with this issue?

**Comment by adityabisht02** [comment]
This repository has the hacktoberfest topic so that should suffice :) , I'll still add the tag
