### ISSUE TITLE
Add a bottom bar fragment

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#2]
![image](https://user-images.githubusercontent.com/89146189/195905135-024fd773-c3e2-478e-80f0-8d7a0d57abe2.png)

**Comment by ashiskumarnaik** [comment]
Hi @adityabisht02 I am ready to work on this issue. can u assign it to me?

**Comment by adityabisht02** [comment]
Sure go ahead!

**Comment by ashiskumarnaik** [comment]
@adityabisht02 make a discord server for beter convo.

**Comment by ashiskumarnaik** [comment]
@adityabisht02 will it be on every activity, just like system UI and toolbar I made ?

**Comment by adityabisht02** [comment]
Yes it will be on every activity except sign in.

**Comment by adityabisht02** [comment]
I am actually not that active on discord ill think about it

**Comment by ashiskumarnaik** [comment]
can you name those icons in the design ?

**Comment by adityabisht02** [comment]
Do u mean for the bottom bar? I can add those icons to drawable.

**Comment by ashiskumarnaik** [comment]
Okay do@adityabisht02 , i will pull it.

**Comment by adityabisht02** [comment]
Done @ashiskumarnaik

**Comment by ashiskumarnaik** [comment]
@adityabisht02 You have not provided the proper svg file of icons. Can I use SVG icons of my own which is goes smooth for the theme properly? ( which will change colour dynamically, I am adding the screenshot )

What is the function of middle button (interaction icon) ? I am asking cause , I want to choose a proper svg for that which will be fine for the design fragments.

**Comment by adityabisht02** [comment]
Yeah u can use your svgs. And the middle button is to navigate to the chat section where users can interact with each other.
