### ISSUE TITLE
Create available shuttles fragment

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#21]
1. Find the fragment_available_shuttles.xml file .
2. The fragment should look like the following:

![image](https://user-images.githubusercontent.com/89146189/196524653-b026954a-dec4-447c-b2b2-1101417aa6dc.png)

3. The Shuttles (eg- Campus to Airport) etc should be a card which be appendable.

**Comment by Summiedev** [comment]
please assign me this

**Comment by adityabisht02** [comment]
Sure go ahead!

**Comment by Summiedev** [comment]
Hello, is there any way i can login to see how it looks like? Just finished writing the code and after running it, i have to sign in

**Comment by adityabisht02** [comment]
username and password are aditya

**Comment by Summiedev** [comment]
Can i readjust the bottom nav? It seems not to be working when switching from one menu to other and it overlaps?

**Comment by adityabisht02** [comment]
Try readjusting it and see how that goes. Remember the card is supposed to be appendable so the we should be able to add as many cards as there are.

**Comment by Summiedev** [comment]
So, I've created a pull request. I've readjusted the bottom nav(it's now working properly) . Also, the last menu in the bottom nav can be removed ( i created it for more accessibility to view Available Shuttle Fragment). The cards are easily appendable in the Java File. Also, the cards design can be modified
