### ISSUE TITLE
Content overlapping with top bar

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#23]
How to replicate:
1. Run the emulator, login credentials aditya and aditya.
2. You will see the following :

![image](https://user-images.githubusercontent.com/89146189/197021060-8b13b4a0-3a73-480a-baca-f8f231c83ad1.png)

The fragment is fragment_meal_reminders,change it accordingly to fit the screen properly.

**Comment by Chandra-Mauli-Sharma** [comment]
@adityabisht02 can you assign this to me.

**Comment by adityabisht02** [comment]
Sure !

**Comment by adityabisht02** [comment]
@Chandra-Mauli-Sharma any updates? I hope u took a pull of the changes as well

**Comment by Chandra-Mauli-Sharma** [comment]
Sorry, I was a little busy, will update today.

**Comment by Chandra-Mauli-Sharma** [comment]
> @Chandra-Mauli-Sharma any updates? I hope u took a pull of the changes as well

In the new Merge, there was a conflict that was not resolved. Do look into it.

**Comment by Chandra-Mauli-Sharma** [comment]
@adityabisht02 you can assign it to someone else.
