### ISSUE TITLE
Create a preloader screen

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#5]
![image](https://user-images.githubusercontent.com/89146189/195999842-1dc16a98-0126-4421-b6fb-4e91514a12a9.png)

It should look like the above with the logo below "BetterPoll"

U can find the logo below -

https://www.figma.com/file/mEZSWJvuUZDB3L3GIgR3q5/Betterpoll-Logo?node-id=0%3A1

**Comment by MohammadKaif1** [comment]
Can I work on this issue?

**Comment by ashiskumarnaik** [comment]
@adityabisht02 assign me this one , let Akash do the admin page , or else I will complete that if he doesn't.

**Comment by MohammadKaif1** [comment]
> @adityabisht02 assign me this one , let Akash do the admin page , or else I will complete that if he doesn't.

Let him decide ....

**Comment by MohammadKaif1** [comment]
I want to work on PreLoader Screen issue..

**Comment by adityabisht02** [comment]
@MohammadKaif1 you can work on this issue I am assigning you.

**Comment by adityabisht02** [comment]
@ashiskumarnaik you have the bottom bar assigned I am also creating new issues right now. This app is only getting started there's a lot of work to be done.

**Comment by MohammadKaif1** [comment]
@adityabisht02 Please give your feedback 

https://user-images.githubusercontent.com/103691849/196007748-7ac4f031-585b-4511-8308-44ac023e4eb4.mp4

**Comment by adityabisht02** [comment]
Looks cool just reduce the size of "BetterPoll" and crop out the logo properly there shouldnt be that white space.

**Comment by MohammadKaif1** [comment]
@adityabisht02 Made some changes. Please review..

https://user-images.githubusercontent.com/103691849/196023795-b795f4e9-24ff-4569-95cb-f5d77439ca84.mp4

**Comment by adityabisht02** [comment]
Looks cool you can make the PR
