### ISSUE TITLE
Create a card for meal reminder

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/BetterPoll-Android#7]
The card view should look like the following :

![image](https://user-images.githubusercontent.com/89146189/196005435-ec73840b-3066-4a25-9ab2-08b7ebe0e279.png)

Use recycler view inside a card view to create this card.

**Comment by HawkItzme** [comment]
Hey @adityabisht02 assign me this issue and please tell how to Login, on putting login credentials it is showing failed message

**Comment by adityabisht02** [comment]
Sure go ahead!

**Comment by HawkItzme** [comment]
Can you explain more about this feature @adityabisht02 like in which activity do i need to add this cardsview ?

**Comment by adityabisht02** [comment]
You can create ab activity_meal_reminders or you can just create the card view , I can create another issue for the activity.

**Comment by adityabisht02** [comment]
The activity will look like this :

![image](https://user-images.githubusercontent.com/89146189/196051270-cdac83c0-bd25-4f16-bd72-d1f11ddd2f62.png)

**Comment by adityabisht02** [comment]
You can either make this whole activity with recycler view or u can make the card

**Comment by HawkItzme** [comment]
Okay

**Comment by HawkItzme** [comment]
Hey bro @adityabisht02 , is this okay? Should i make the PR ?

https://user-images.githubusercontent.com/86477458/196060558-a39d0526-7f37-43f6-af17-56ce87e822c6.mp4

**Comment by adityabisht02** [comment]
looks great u can go ahead!

**Comment by HawkItzme** [comment]
okay
